name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabi qemu-user

    - name: build
      run: make build
    - name: install test deps
      run: |
        sudo apt update
        sudo apt install python3
        sudo apt install python3-pytest

    - name: run tests x86
      run: |
        python3.8 -m venv test
        source test/bin/activate
        pip install --upgrade pip
        pip install -r test/requirements.txt
        make build-x86
        make test
    - name: run tests arm64
      run: |
        python3.8 -m venv test
        source test/bin/activate
        pip install --upgrade pip
        pip install -r test/requirements.txt
        make build-arm64
        make test
    - name: run tests arm32
      run: |
        python3.8 -m venv test
        source test/bin/activate
        pip install --upgrade pip
        pip install -r test/requirements.txt
        make build-arm32
        # make test
